import { BrowserRouter, Routes, Route } from "react-router-dom";
import React from "react";
import { createRoot } from "react-dom/client";
import Home from "./pages/Home";
import Playlist from "./pages/Playlist";

export default function App() {
  const songCard = [
    {
      id: 1,
      image: "https://i.scdn.co/image/ab67616d00001e02ff9ca10b55ce82ae553c8228",
      name: "The Chainsmokers",
      desc: "Hottest hits in USA",
      songList: [
        {
          id: 1,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },

        {
          id: 2,
          image: "https://via.placeholder.com/40x40",
          name: "Business",
          author: "Tiesto",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 3,
          image: "https://via.placeholder.com/40x40",
          name: "Phonk 2d",
          author: "Japanio",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 4,
          image: "https://via.placeholder.com/40x40",
          name: "Family",
          author: "Vin Diesel",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 5,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 6,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "6:00",
        },
        {
          id: 7,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 8,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "5:30",
        },
        {
          id: 9,
          image: "https://via.placeholder.com/40x40",
          name: "Goodbyes",
          author: "Post Malone",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 10,
          image: "https://via.placeholder.com/40x40",
          name: "Lost in Japan",
          author: "Shawn Mendes",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "3:30",
        },
      ],
    },
    {
      id: 2,
      image: "https://loremflickr.com/cache/resized/65535_52286707607_f152963408_420_340_nofilter.jpg",
      name: "Khalid Mix",
      desc: "Hottest hits in USA",
      songList: [
        {
          id: 1,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },

        {
          id: 2,
          image: "https://via.placeholder.com/40x40",
          name: "Business",
          author: "Tiesto",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 3,
          image: "https://via.placeholder.com/40x40",
          name: "Phonk 2d",
          author: "Japanio",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 4,
          image: "https://via.placeholder.com/40x40",
          name: "Family",
          author: "Vin Diesel",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 5,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 6,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "6:00",
        },
        {
          id: 7,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 8,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "5:30",
        },
        {
          id: 9,
          image: "https://via.placeholder.com/40x40",
          name: "Goodbyes",
          author: "Post Malone",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 10,
          image: "https://via.placeholder.com/40x40",
          name: "Lost in Japan",
          author: "Shawn Mendes",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "3:30",
        },
      ],
    },
    {
      id: 3,
      image: "https://via.placeholder.com/158x158",
      name: "All time rock",
      desc: "Hottest hits in USA",
      songList: [
        {
          id: 1,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },

        {
          id: 2,
          image: "https://via.placeholder.com/40x40",
          name: "Business",
          author: "Tiesto",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 3,
          image: "https://via.placeholder.com/40x40",
          name: "Phonk 2d",
          author: "Japanio",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 4,
          image: "https://via.placeholder.com/40x40",
          name: "Family",
          author: "Vin Diesel",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 5,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 6,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "6:00",
        },
        {
          id: 7,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 8,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "5:30",
        },
        {
          id: 9,
          image: "https://via.placeholder.com/40x40",
          name: "Goodbyes",
          author: "Post Malone",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 10,
          image: "https://via.placeholder.com/40x40",
          name: "Lost in Japan",
          author: "Shawn Mendes",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "3:30",
        },
      ],
    },
    {
      id: 4,
      image: "https://via.placeholder.com/158x158",
      name: "Good vibes",
      desc: "Hottest hits in USA",
      songList: [
        {
          id: 1,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },

        {
          id: 2,
          image: "https://via.placeholder.com/40x40",
          name: "Business",
          author: "Tiesto",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 3,
          image: "https://via.placeholder.com/40x40",
          name: "Phonk 2d",
          author: "Japanio",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 4,
          image: "https://via.placeholder.com/40x40",
          name: "Family",
          author: "Vin Diesel",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 5,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 6,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "6:00",
        },
        {
          id: 7,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 8,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "5:30",
        },
        {
          id: 9,
          image: "https://via.placeholder.com/40x40",
          name: "Goodbyes",
          author: "Post Malone",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 10,
          image: "https://via.placeholder.com/40x40",
          name: "Lost in Japan",
          author: "Shawn Mendes",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "3:30",
        },
      ],
    },
    {
      id: 5,
      image: "https://via.placeholder.com/158x158",
      name: "This is Lauv",
      desc: "Hottest hits in USA",
      songList: [
        {
          id: 1,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },

        {
          id: 2,
          image: "https://via.placeholder.com/40x40",
          name: "Business",
          author: "Tiesto",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 3,
          image: "https://via.placeholder.com/40x40",
          name: "Phonk 2d",
          author: "Japanio",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 4,
          image: "https://via.placeholder.com/40x40",
          name: "Family",
          author: "Vin Diesel",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 5,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 6,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "6:00",
        },
        {
          id: 7,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 8,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "5:30",
        },
        {
          id: 9,
          image: "https://via.placeholder.com/40x40",
          name: "Goodbyes",
          author: "Post Malone",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 10,
          image: "https://via.placeholder.com/40x40",
          name: "Lost in Japan",
          author: "Shawn Mendes",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "3:30",
        },
      ],
    },
    {
      id: 6,
      image: "https://via.placeholder.com/158x158",
      name: "Game Changer",
      desc: "Hottest hits in USA",
      songList: [
        {
          id: 1,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },

        {
          id: 2,
          image: "https://via.placeholder.com/40x40",
          name: "Business",
          author: "Tiesto",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 3,
          image: "https://via.placeholder.com/40x40",
          name: "Phonk 2d",
          author: "Japanio",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 4,
          image: "https://via.placeholder.com/40x40",
          name: "Family",
          author: "Vin Diesel",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 5,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 6,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "6:00",
        },
        {
          id: 7,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 8,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "5:30",
        },
        {
          id: 9,
          image: "https://via.placeholder.com/40x40",
          name: "Goodbyes",
          author: "Post Malone",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 10,
          image: "https://via.placeholder.com/40x40",
          name: "Lost in Japan",
          author: "Shawn Mendes",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "3:30",
        },
      ],
    },
    {
      id: 7,
      image: "https://via.placeholder.com/158x158",
      name: "Play School Hits",
      desc: "Hottest hits in USA",
      songList: [
        {
          id: 1,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },

        {
          id: 2,
          image: "https://via.placeholder.com/40x40",
          name: "Business",
          author: "Tiesto",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 3,
          image: "https://via.placeholder.com/40x40",
          name: "Phonk 2d",
          author: "Japanio",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 4,
          image: "https://via.placeholder.com/40x40",
          name: "Family",
          author: "Vin Diesel",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 5,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 6,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "6:00",
        },
        {
          id: 7,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 8,
          image: "https://via.placeholder.com/40x40",
          name: "We are good",
          author: "Dua Lipa",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "5:30",
        },
        {
          id: 9,
          image: "https://via.placeholder.com/40x40",
          name: "Goodbyes",
          author: "Post Malone",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: false,
          duration: "2:30",
        },
        {
          id: 10,
          image: "https://via.placeholder.com/40x40",
          name: "Lost in Japan",
          author: "Shawn Mendes",
          album_name: "Nostalgia Future",
          date_added: "12 Dec 2022",
          isLiked: true,
          duration: "3:30",
        },
      ],
    },
  ];
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Home songCard={songCard} />} />
        {/* Add a for loop for custom url routes for same layout and each playlist */}

        {songCard.map((item) => {
          return (
            <Route
              key={item.id}
              path={`/playlist/${item.name}`}
              element={<Playlist title={item.name} songList={item.songList} image={item.image} />}
            />
          );
        })}
      </Routes>
    </BrowserRouter>
  );
}

const root = createRoot(document.getElementById("root"));
root.render(<App />);
